"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints
${imports if imports else ""}

# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = ${repr(up_revision)}
down_revision: Union[str, None] = ${repr(down_revision)}
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    ${downgrades if downgrades else "pass"}