import { EnumItemFormat, EnumWordItemGroup } from "../../types/words";

// tooltips for menu
export interface WordStrategyDefinition {
  id: string;
  name: string;
  description: string;
  stemExample: string;
  keyExample: string;
  supportedFormats: readonly EnumItemFormat[];
  group: EnumWordItemGroup;
  pairId?: string;
  pairName?: string;
  pairDescription?: string;
  pairStemExample?: string;
  pairKeyExample?: string;
  pairSupportedFormats?: readonly EnumItemFormat[];
}

export const WordStrategyTooltips: WordStrategyDefinition[] = [
  {
    id: "LEM_TO_POS",
    name: "Lemma → Part of Speech",
    description: "Identify the part of speech of a given word.",
    stemExample: "Identify the part of speech of дерево.",
    keyExample: "Noun",
    supportedFormats: ["flashcard", "mcq"],
    group: "General",
    pairId: "POS_TO_LEM",
    pairName: "Part of Speech → Lemma",
    pairDescription: "Identify an example of a part of speech.",
    pairStemExample: "Identify the word that is an adjective.",
    pairKeyExample: "красный",
    pairSupportedFormats: ["mcq"],
  },
  {
    id: "LEM_TO_DEF",
    name: "Lemma → Definition",
    description: "Identify the definition of a given word.",
    stemExample: "What is the definition of искать?",
    keyExample: "to search, to look for",
    supportedFormats: ["flashcard", "mcq"],
    group: "General",
    pairId: "DEF_TO_LEM",
    pairName: "Definition → Lemma",
    pairDescription: "Identify a word by its definition.",
    pairStemExample: "What word means 'to think, to believe, to count'?",
    pairKeyExample: "считать",
    pairSupportedFormats: ["fitb", "flashcard", "mcq"],
  },
  {
    id: "LEM_TO_PRON",
    name: "Lemma → Pronunciation",
    description: "Identify the pronunciation of a given word.",
    stemExample: "What is the proper romanization pronunciation of 'сестра'?",
    keyExample: "'sestrá'",
    supportedFormats: ["flashcard", "mcq"],
    group: "General",
    pairId: "PRON_TO_LEM",
    pairName: "Pronunciation → Lemma",
    pairDescription: "Identify a word by its pronunciation.",
    pairStemExample: "What word is said as '[sɐɐpˈɕːenʲɪje]' (IPA)?",
    pairKeyExample: "сообщение",
    pairSupportedFormats: ["fitb", "flashcard", "mcq"],
  },
  {
    id: "LEM_LEM_TO_REL",
    name: "Lemma + Lemma → Relationship",
    description: "Identify the relationship of two given words.",
    stemExample: "What is the relationship of 'погиба́ть' to 'умере́ть'?",
    keyExample: "synonym",
    supportedFormats: ["flashcard", "mcq"],
    group: "General",
    pairId: "REL_TO_LEM_LEM",
    pairName: "Relationship → Lemma + Lemma",
    pairDescription: "Identify an example pair of a linguistic relationship.",
    pairStemExample: "What is an example of antonyms?",
    pairKeyExample: "ма́ленький, большо́й",
    pairSupportedFormats: ["mcq"],
  },
  //   {
  //     id: "ADJV_FORM_TO_TYPE",
  //     name: "Adjectival Form → Comparative Type",
  //     group: "Adjectives",
  //     description:
  //       "Identify the type (comparative | superlative) given an adjective's form.",
  //     stemExample: "",
  //     keyExample: "",
  //     supportedFormats: ["flashcard", "mcq", "fitb"],
  //     pairId: "ADJV_TYPE_TO_LEM",
  //     pairName: "Part of Speech → Lemma",
  //     pairDescription: "Identify the base adjective given a comparative form.",
  //     pairStemExample: "",
  //     pairKeyExample: "",
  //     pairSupportedFormats: ["fitb", "flashcard", "mcq"]
  //   },
  {
    id: "ADJV_FORM_TO_GRAM",
    name: "Adjective (base) + Adjective (declined) → Grammar description",
    group: "Adjectives",
    description: "Identify the declension of an adjectival form.",
    stemExample: "",
    keyExample: "",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "ADJV_GRAM_TO_FORM",
    pairName: "Adjective (base) + Grammar description → Adjective (declined)",
    pairDescription:
      "Identify the form of an adjective given its base form and a declension type.",
    pairStemExample: "",
    pairKeyExample: "",
    pairSupportedFormats: ["flashcard", "mcq", "fitb"],
  },
  {
    id: "NOUN_TO_GEND",
    name: "Noun → Gender",
    group: "Nouns",
    description: "Identify the gender of a given noun.",
    stemExample: "What is the gender of 'ночь'?",
    keyExample: "feminine",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "GEND_TO_NOUN",
    pairName: "Gender → Noun",
    pairDescription: "Identify an example noun of a given gender.",
    pairStemExample: "Which of the following nouns is neuter?",
    pairKeyExample: "общество",
    pairSupportedFormats: ["mcq"],
  },
  {
    id: "NOUN_TO_ANIM",
    name: "Noun → Animacy",
    group: "Nouns",
    description: "Identify the animacy of a given noun.",
    stemExample: "What is the animacy of the word 'кот'?",
    keyExample: "animate",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "ANIM_TO_NOUN",
    pairName: "Animacy → Noun",
    pairDescription: "Identify an example noun of a given animacy.",
    pairStemExample: "Which of the following nouns is inanimate?",
    pairKeyExample: "каша",
    pairSupportedFormats: ["mcq"],
  },
  {
    id: "NOUN_FORM_TO_GRAM",
    name: "Noun (base) + Noun (declined) → Grammar description",
    group: "Nouns",
    description: "Identify the declension of a given noun form.",
    stemExample: "знание → знаний",
    keyExample: "genitive plural",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "NOUN_GRAM_TO_FORM",
    pairName: "Noun (base) + Grammar description → Noun (declined)",
    pairDescription: "Identify an example noun of a given animacy.",
    pairStemExample: "What is the dative singular form of 'брат'?",
    pairKeyExample: "брату",
    pairSupportedFormats: ["fitb", "flashcard", "mcq"],
  },
  //   {
  //     id: "NOUN_TO_DMIN_FORM",
  //     // pairId: "",
  //     name: "Noun → Diminutive Form",
  //     group: "Nouns",
  //     description: "Identify the diminutive form of a given noun.",
  //     stemExample: "What is the diminutive form of 'день'?",
  //     keyExample: "денёк",
  //     // pairDescription: "",
  //     supportedFormats: ["flashcard", "mcq", "fitb"],
  //   },
  //   {
  //     id: "PART_FORM_TO_TYPE",
  //     name: "Participle → Type",
  //     group: "Participles",
  //     description: "Identify the tense and voice of a given participle.",
  //     stemExample: "",
  //     keyExample: "",
  //     supportedFormats: ["flashcard", "mcq"],
  //     pairId: "PART_TYPE_TO_FORM",
  //     pairName: "Participle → Type",
  //     pairDescription:
  //       "Identify an example of a given participle tense and voice.",
  //     pairStemExample: "",
  //     pairKeyExample: "",
  //     pairSupportedFormats: ["fitb", "flashcard", "mcq"]
  //   },
  {
    id: "VERB_TO_ASPT",
    name: "Verb → Aspect",
    group: "Verbs",
    description: "Identify the aspect of a given verb.",
    stemExample: "",
    keyExample: "",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "ASPT_TO_VERB",
    pairName: "Aspect → Verb",
    pairDescription: "Identify an example of a given verbal aspect.",
    pairStemExample: "Which of the following is perfective aspect?",
    pairKeyExample: "побыть",
    pairSupportedFormats: ["mcq"],
  },
  {
    id: "VERB_PAIR_TO_REL",
    name: "Verb Pair → Relationship",
    group: "Verbs",
    description: "Identify the relationship of a given verb pair.",
    stemExample: "What is the relationship of '' to ''?",
    keyExample: "",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "VERB_TO_ASPT_PAIR",
    pairName: "Verb Relationship → Pair",
    pairDescription: "Identify the aspectual pair of a given verb.",
    pairStemExample: "",
    pairKeyExample: "",
    pairSupportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "VERB_TO_TYPE",
    name: "Verb → Type",
    group: "Verbs",
    description: "Identify the Type of a given verb.",
    stemExample: "What verb type is 'дрейфовать'?",
    keyExample: "Type I",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "TYPE_TO_VERB",
    pairName: "Type → Verb",
    pairDescription: "Identify an example of a given verbal Type.",
    pairStemExample: "Which of the following is a Type-II verb?",
    pairKeyExample: "'ходить'",
    pairSupportedFormats: ["mcq"],
  },
  //   {
  //     id: "VERB_TO_CONJ_FORM",
  //     name: "Verb → Conjugated Form",
  //     group: "Verbs",
  //     description: "Identify the form of a given verb and conjugation.",
  //     stemExample: "",
  //     keyExample: "",
  //     supportedFormats: ["flashcard", "mcq", "fitb"],
  //   },
  {
    id: "VERB_TO_TNRF",
    name: "Verb → Transitivity / Reflexivity",
    group: "Verbs",
    description: "Identify the transitivity / reflexivity of a given verb.",
    stemExample: "Is the verb '' intransitive, transitive, or reflexive?",
    keyExample: "",
    supportedFormats: ["flashcard", "mcq"],
    pairId: "TNRF_TO_VERB",
    pairName: "Transitivity / Reflexivity Verb",
    pairDescription:
      "Identify an example of a (in)transitive / reflexive verb.",
    pairStemExample: "",
    pairKeyExample: "",
    pairSupportedFormats: ["mcq"],
  },
];
