import { EnumItemFormat, EnumWordItemGroup } from "../../types/words";

// tooltips for menu
export interface WordStrategyDefinition {
  id: string;
  pairId?: string;
  name: string;
  group: EnumWordItemGroup;
  description: string;
  stemExample: string;
  keyExample: string;
  supportedFormats: EnumItemFormat[];
  pairDescription?: string;
  pairStemExample?: string;
  pairKeyExample?: string;
  pairSupportedFormats?: EnumItemFormat[];
}

export const WordStrategyTooltips: WordStrategyDefinition[] = [
  {
    id: "LEM_TO_POS",
    pairId: "POS_TO_LEM",
    name: "Lemma → Part of Speech",
    group: "General",
    description: "Identify the part of speech of a given word.",
    stemExample: "Identify the part of speech of дерево.",
    keyExample: "Noun",
    pairDescription: "Identify an example of a part of speech.",
    pairStemExample: "Identify the word that is an adjective.",
    pairKeyExample: "красный",
    supportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "LEM_TO_DEF",
    pairId: "DEF_TO_LEM",
    name: "Lemma → Definition",
    group: "General",
    description: "Identify the definition of a given word.",
    stemExample: "What is the definition of искать?",
    keyExample: "to search, to look for",
    pairDescription: "Identify a word by its definition.",
    pairStemExample: "What word means 'to think, to believe, to count'?",
    pairKeyExample: "считать",
    supportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "LEM_TO_PRON",
    pairId: "PRON_TO_LEM",
    name: "Lemma → Pronunciation",
    group: "General",
    description: "Identify the pronunciation of a given word.",
    stemExample: "What is the proper romanization pronunciation of 'сестра'?",
    keyExample: "'sestrá'",
    pairDescription: "Identify a word by its pronunciation.",
    pairStemExample: "What word is said as '[sɐɐpˈɕːenʲɪje]' (IPA)?",
    pairKeyExample: "сообщение",
    supportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "LEM_LEM_TO_REL",
    pairId: "REL_TO_LEM_LEM",
    name: "Lemma + Lemma → Relationship",
    group: "General",
    description: "Identify the relationship of two given words.",
    stemExample: "What is the relationship of 'погиба́ть' to 'умере́ть'?",
    keyExample: "synonym",
    pairDescription: "Identify an example pair of a linguistic relationship.",
    pairStemExample: "What is an example of antonyms?",
    pairKeyExample: "ма́ленький, большо́й",
    supportedFormats: ["flashcard", "mcq"],
  },
  //   {
  //     id: "ADJV_FORM_TO_TYPE",
  //     pairId: "ADJV_TYPE_TO_LEM",
  //     name: "Adjectival Form → Comparative Type",
  //     group: "Adjectives",
  //     description:
  //       "Identify the type (comparative | superlative) given an adjective's form.",
  //     stemExample: "",
  //     keyExample: "",
  //     pairDescription: "Identify the base adjective given a comparative form.",
  //     pairStemExample: "",
  //     pairKeyExample: "",
  //     supportedFormats: ["flashcard", "mcq", "fitb"],
  //   },
  {
    id: "ADJV_FORM_TO_GRAM",
    pairId: "ADJV_GRAM_TO_FORM",
    name: "Adjective (base) + Adjective (declined) → Declension form",
    group: "Adjectives",
    description:
      "Identify the declension type of an adjectival form given its base form.",
    stemExample: "",
    keyExample: "",
    pairDescription:
      "Identify the form of an adjective given its base form and a declension type.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq", "fitb"],
  },
  {
    id: "NOUN_TO_GEND",
    pairId: "GEND_TO_NOUN",
    name: "Noun → Gender",
    group: "Nouns",
    description: "Identify the gender of a given noun.",
    stemExample: "",
    keyExample: "",
    pairDescription: "Identify an example noun of a given gender.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "NOUN_TO_ANIM",
    pairId: "ANIM_TO_NOUN",
    name: "Noun → Animacy",
    group: "Nouns",
    description: "Identify the animacy of a given noun.",
    stemExample: "",
    keyExample: "",
    pairDescription: "Identify an example noun of a given animacy.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "NOUN_FORM_TO_GRAM",
    pairId: "NOUN_GRAM_TO_FORM",
    name: "Noun → Animacy",
    group: "Nouns",
    description: "Identify the animacy of a given noun.",
    stemExample: "",
    keyExample: "",
    pairDescription: "Identify an example noun of a given animacy.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq"],
  },
  //   {
  //     id: "NOUN_TO_DMIN_FORM",
  //     // pairId: "",
  //     name: "Noun → Diminutive Form",
  //     group: "Nouns",
  //     description: "Identify the diminutive form of a given noun.",
  //     stemExample: "",
  //     keyExample: "",
  //     // pairDescription: "",
  //     supportedFormats: ["flashcard", "mcq", "fitb"],
  //   },
  //   {
  //     id: "PART_FORM_TO_TYPE",
  //     pairId: "PART_TYPE_TO_FORM",
  //     name: "Participle → Type",
  //     group: "Participles",
  //     description: "Identify the tense and voice of a given participle.",
  //     stemExample: "",
  //     keyExample: "",
  //     pairDescription:
  //       "Identify an example of a given participle tense and voice.",
  //     pairStemExample: "",
  //     pairKeyExample: "",
  //     supportedFormats: ["flashcard", "mcq"],
  //   },
  {
    id: "VERB_TO_ASPT",
    pairId: "ASPT_TO_VERB",
    name: "Verb → Aspect",
    group: "Verbs",
    description: "Identify the aspect of a given verb.",
    stemExample: "",
    keyExample: "",
    pairDescription: "Identify an example of a given verbal aspect.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "VERB_PAIR_TO_REL",
    pairId: "VERB_TO_ASPT_PAIR",
    name: "Verb → Aspect",
    group: "Verbs",
    description: "Identify the relationship of a given verb pair.",
    stemExample: "",
    keyExample: "",
    pairDescription: "Identify the aspectual pair of a given verb.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq"],
  },
  {
    id: "VERB_TO_TYPE",
    pairId: "TYPE_TO_VERB",
    name: "Verb → Aspect",
    group: "Verbs",
    description: "Identify the aspect of a given verb.",
    stemExample: "",
    keyExample: "",
    pairDescription: "Identify an example of a given verbal aspect.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq"],
  },
  //   {
  //     id: "VERB_TO_CONJ_FORM",
  //     // pairId: "",
  //     name: "Verb → Conjugated Form",
  //     group: "Verbs",
  //     description: "Identify the form of a given verb and conjugation.",
  //     stemExample: "",
  //     keyExample: "",
  //     // pairDescription: "",
  //     supportedFormats: ["flashcard", "mcq", "fitb"],
  //   },
  {
    id: "VERB_TO_TNRF",
    pairId: "TNRF_TO_VERB",
    name: "Verb → Transitivity / Reflexivity",
    group: "Verbs",
    description: "Identify the transitivity / reflexivity of a given verb.",
    stemExample: "",
    keyExample: "",
    pairDescription:
      "Identify an example of a (in)transitive / reflexive verb.",
    pairStemExample: "",
    pairKeyExample: "",
    supportedFormats: ["flashcard", "mcq"],
  },
];
