[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "alite"
version = "0.1.0"
description = "Autonomous Learning And Teaching Engine"
authors = [{name = "Aaron Thompson", email = "aaron.thompson@dliflc.edu"}]
readme = "../../README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "sqlmodel",
    "psycopg2-binary",
    "pandas",
    "beautifulsoup4",
    "lxml",
    "python-dotenv",
    "httpx",
    "pydantic-settings",
    "alembic"
]

[tool.poetry]
packages = [{include = "alite_backend", from = "src"}]

[tool.poetry.group.dev.dependencies]
jupyterlab = "^4.0.0"
black = "^25.1.0"
pytest = "^8.0.0"
pylint = "^3.3.0"
pre-commit = "^4.0.0"
bandit = "^1.8.6"
ipykernel = "^7.2.0"
