"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints
from sqlalchemy.dialects import postgresql

# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = '148ae53447f3'
down_revision: Union[str, None] = 'a09e7cfd6c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lookup_queue', 'rel_type',
               existing_type=postgresql.ENUM('ADJECTIVE_OF', 'ABSTRACT_NOUN_OF', 'ADVERB_OF', 'REL_ADJV_OF', 'NOUN_FROM_VERB_OF', 'PERFECTIVE_PAIR_OF', 'IMPERFECTIVE_PAIR_OF', 'SYNONYM_OF', 'ANTONYM_OF', name='enumrellemtype'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('lookup_queue', 'rel_type',
               existing_type=postgresql.ENUM('ADJECTIVE_OF', 'ABSTRACT_NOUN_OF', 'ADVERB_OF', 'REL_ADJV_OF', 'NOUN_FROM_VERB_OF', 'PERFECTIVE_PAIR_OF', 'IMPERFECTIVE_PAIR_OF', 'SYNONYM_OF', 'ANTONYM_OF', name='enumrellemtype'),
               nullable=False)
    # ### end Alembic commands ###