"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints


# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = '3a55bf200a6d'
down_revision: Union[str, None] = '02431b21f028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lemmas_lem_text_trgm'), table_name='lemmas', postgresql_ops={'lem_text': 'gin_trgm_ops'}, postgresql_using='gin')
    op.add_column('student_responses', sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_student_responses_user_id'), table_name='student_responses')
    op.drop_constraint(op.f('student_responses_user_id_fkey'), 'student_responses', type_='foreignkey')
    op.drop_column('student_responses', 'user_id')
    op.drop_column('student_responses', 'selection')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=15),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=32),
               nullable=False)
    op.add_column('student_responses', sa.Column('selection', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('student_responses', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('student_responses_user_id_fkey'), 'student_responses', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_student_responses_user_id'), 'student_responses', ['user_id'], unique=False)
    op.drop_column('student_responses', 'response')
    op.create_index(op.f('ix_lemmas_lem_text_trgm'), 'lemmas', ['lem_text'], unique=False, postgresql_ops={'lem_text': 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###