"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints
from sqlalchemy.dialects import postgresql

# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = '4dd19eb53a43'
down_revision: Union[str, None] = 'bf32aadbd7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_options',
    sa.Column('option_uuid', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('option_uuid')
    )
    op.create_index(op.f('ix_item_options_item_id'), 'item_options', ['item_id'], unique=False)
    op.alter_column('items', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('items', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('items', 'finish_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_items_difficulty'), table_name='items')
    op.create_index(op.f('ix_items_order_in_ex'), 'items', ['order_in_ex'], unique=False)
    op.drop_column('items', 'key')
    op.drop_column('items', 'difficulty')
    op.drop_column('items', 'distractors')
    op.add_column('student_responses', sa.Column('attempt_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_responses', 'attempt_num')
    op.add_column('items', sa.Column('distractors', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('items', sa.Column('difficulty', postgresql.ENUM('EASY', 'MEDIUM', 'DIFFICULT', name='enumitemdifficulty'), autoincrement=False, nullable=False))
    op.add_column('items', sa.Column('key', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_items_order_in_ex'), table_name='items')
    op.create_index(op.f('ix_items_difficulty'), 'items', ['difficulty'], unique=False)
    op.alter_column('items', 'finish_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('items', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('items', 'prompt',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_item_options_item_id'), table_name='item_options')
    op.drop_table('item_options')
    # ### end Alembic commands ###