"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints
from sqlalchemy.dialects import postgresql

# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = '63f977a06cdc'
down_revision: Union[str, None] = 'abd901560985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'item_type',
               existing_type=postgresql.ENUM('LEM_TO_POS', 'POS_TO_LEM', 'LEM_TO_DEF', 'DEF_TO_LEM', 'LEM_TO_PRON', 'PRON_TO_LEM', 'LEM_LEM_TO_REL', 'REL_TO_LEM_LEM', 'ADJV_FORM_TO_TYPE', 'ADJV_TYPE_TO_LEM', 'ADJV_FORM_TO_GRAM', 'ADJV_GRAM_TO_FORM', 'NOUN_TO_GEND', 'GEND_TO_NOUN', 'NOUN_TO_ANIM', 'ANIM_TO_NOUN', 'NOUN_FORM_TO_GRAM', 'NOUN_GRAM_TO_FORM', 'NOUN_TO_DMIN_FORM', 'PART_TYPE_TO_FORM', 'PART_FORM_TO_TYPE', 'VERB_TO_ASPT', 'ASPT_TO_VERB', 'VERB_PAIR_TO_REL', 'VERB_TO_ASPT_PAIR', 'VERB_TO_TYPE', 'TYPE_TO_VERB', 'VERB_TO_CONJ_FORM', 'VERB_TO_TNRF', 'TNRF_TO_VERB', name='enumworditemtype'),
               type_=sa.String(length=64),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'item_type',
               existing_type=sa.String(length=64),
               type_=postgresql.ENUM('LEM_TO_POS', 'POS_TO_LEM', 'LEM_TO_DEF', 'DEF_TO_LEM', 'LEM_TO_PRON', 'PRON_TO_LEM', 'LEM_LEM_TO_REL', 'REL_TO_LEM_LEM', 'ADJV_FORM_TO_TYPE', 'ADJV_TYPE_TO_LEM', 'ADJV_FORM_TO_GRAM', 'ADJV_GRAM_TO_FORM', 'NOUN_TO_GEND', 'GEND_TO_NOUN', 'NOUN_TO_ANIM', 'ANIM_TO_NOUN', 'NOUN_FORM_TO_GRAM', 'NOUN_GRAM_TO_FORM', 'NOUN_TO_DMIN_FORM', 'PART_TYPE_TO_FORM', 'PART_FORM_TO_TYPE', 'VERB_TO_ASPT', 'ASPT_TO_VERB', 'VERB_PAIR_TO_REL', 'VERB_TO_ASPT_PAIR', 'VERB_TO_TYPE', 'TYPE_TO_VERB', 'VERB_TO_CONJ_FORM', 'VERB_TO_TNRF', 'TNRF_TO_VERB', name='enumworditemtype'),
               existing_nullable=False)
    # ### end Alembic commands ###