"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints
from sqlalchemy.dialects import postgresql

# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = '993c9078c6cb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('def_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('def_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('def_text')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('examples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ex_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ex_text')
    )
    op.create_table('gram_props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('irregular', sa.Boolean(), nullable=False),
    sa.Column('gram_tense', sa.Enum('PAST', 'PRESENT', 'FUTURE', name='enumgramtense'), nullable=True),
    sa.Column('gram_num', sa.Enum('SINGULAR', 'PLURAL', name='enumgramnum'), nullable=True),
    sa.Column('gram_gender', sa.Enum('MASCULINE', 'NEUTER', 'FEMININE', 'DUAL', name='enumgramgender'), nullable=True),
    sa.Column('conj_person', sa.Enum('FIRST', 'SECOND', 'THIRD', name='enumconjperson'), nullable=True),
    sa.Column('verb_mood', sa.Enum('INDICATIVE', 'IMPERATIVE', name='enumverbmood'), nullable=True),
    sa.Column('subst_case', sa.Enum('NOMINATIVE', 'GENITIVE', 'ACCUSATIVE', 'DATIVE', 'INSTRUMENTAL', 'PREPOSITIONAL', 'VOCATIVE', 'LOCATIVE', 'PARTITIVE', name='enumsubstcase'), nullable=True),
    sa.Column('alt_adjv_type', sa.Enum('COMPARATIVE', 'SUPERLATIVE', 'SHORT', name='enumaltadjvtype'), nullable=True),
    sa.Column('alt_noun_type', sa.Enum('DIMINUTIVE', 'AUGMENTATIVE', 'COLLECTIVE', 'PAUCAL', 'PEJORATIVE', name='enumaltnountype'), nullable=True),
    sa.Column('part_type', sa.Enum('ADJECTIVAL', 'ADVERBIAL', name='enumparttype'), nullable=True),
    sa.Column('part_voice', sa.Enum('ACTIVE', 'PASSIVE', name='enumpartvoice'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gram_tense', 'gram_num', 'gram_gender', 'conj_person', 'verb_mood', 'subst_case', 'alt_adjv_type', 'alt_noun_type', 'part_type', 'part_voice', name='unique_grammar')
    )
    op.create_table('lemmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('entry_key', sa.Uuid(), nullable=False),
    sa.Column('lem_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lem_canon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pos', sa.Enum('ADJECTIVE', 'ADVERB', 'COM', 'CONJUNCTION', 'INTERJECTION', 'NOUN', 'NUMERAL', 'PARTICIPLE', 'PARTICLE', 'PREPOSITION', 'PRONOUN', 'VERB', 'UNKNOWN', name='enumpartofspeech'), nullable=False),
    sa.Column('noun_gender', sa.Enum('MASCULINE', 'NEUTER', 'FEMININE', 'DUAL', name='enumgramgender'), nullable=True),
    sa.Column('noun_animacy', sa.Boolean(), nullable=True),
    sa.Column('verb_aspect', sa.Enum('IMPERFECTVE', 'PERFECTIVE', 'DUAL', name='enumverbaspect'), nullable=True),
    sa.Column('verb_conj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('verb_type', sa.Enum('TYPE_I', 'TYPE_II', name='enumverbtype'), nullable=True),
    sa.Column('verb_trans_refl', sa.Enum('INTRANSITIVE', 'TRANSITIVE', 'REFLEXIVE', name='enumverbtransrefl'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'entry_key', name='unique_lemma')
    )
    op.create_index(op.f('ix_lemmas_entry_key'), 'lemmas', ['entry_key'], unique=True)
    op.create_index(op.f('ix_lemmas_lem_canon'), 'lemmas', ['lem_canon'], unique=False)
    op.create_index(op.f('ix_lemmas_lem_text'), 'lemmas', ['lem_text'], unique=False)
    op.create_table('lexicon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lex_text', sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
    sa.Column('lex_text_clean', sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lexicon_lex_text'), 'lexicon', ['lex_text'], unique=True)
    op.create_index(op.f('ix_lexicon_lex_text_clean'), 'lexicon', ['lex_text_clean'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name')
    )
    op.create_table('pronunciations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pron_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pron_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('pron_type', sa.Enum('IPA', 'ROMANIZATION', name='enumprontype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pron_text')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('group_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_groups_group_name'), 'user_groups', ['group_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_role', sa.String(length=32), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias')
    )
    op.create_index('ix_user_settings_gin', 'users', ['settings'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('def_exs',
    sa.Column('def_id', sa.Integer(), nullable=False),
    sa.Column('ex_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['def_id'], ['definitions.id'], ),
    sa.ForeignKeyConstraint(['ex_id'], ['examples.id'], ),
    sa.PrimaryKeyConstraint('def_id', 'ex_id')
    )
    op.create_index(op.f('ix_def_exs_def_id'), 'def_exs', ['def_id'], unique=False)
    op.create_index(op.f('ix_def_exs_ex_id'), 'def_exs', ['ex_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finish_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_user_id'), 'exercises', ['user_id'], unique=False)
    op.create_table('lem_defs',
    sa.Column('lem_id', sa.Integer(), nullable=False),
    sa.Column('def_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['def_id'], ['definitions.id'], ),
    sa.ForeignKeyConstraint(['lem_id'], ['lemmas.id'], ),
    sa.PrimaryKeyConstraint('lem_id', 'def_id')
    )
    op.create_index(op.f('ix_lem_defs_def_id'), 'lem_defs', ['def_id'], unique=False)
    op.create_index(op.f('ix_lem_defs_lem_id'), 'lem_defs', ['lem_id'], unique=False)
    op.create_table('lem_prons',
    sa.Column('lem_id', sa.Integer(), nullable=False),
    sa.Column('pron_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lem_id'], ['lemmas.id'], ),
    sa.ForeignKeyConstraint(['pron_id'], ['pronunciations.id'], ),
    sa.PrimaryKeyConstraint('lem_id', 'pron_id')
    )
    op.create_index(op.f('ix_lem_prons_lem_id'), 'lem_prons', ['lem_id'], unique=False)
    op.create_index(op.f('ix_lem_prons_pron_id'), 'lem_prons', ['pron_id'], unique=False)
    op.create_table('lem_rels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('rel_type', sa.Enum('ADJECTIVE_OF', 'ABSTRACT_NOUN_OF', 'ADVERB_OF', 'REL_ADJV_OF', 'NOUN_FROM_VERB_OF', 'PERFECTIVE_PAIR_OF', 'IMPERFECTIVE_PAIR_OF', 'SYNONYM_OF', 'ANTONYM_OF', name='enumrellemtype'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['lemmas.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['lemmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lem_rels_source_id'), 'lem_rels', ['source_id'], unique=False)
    op.create_index(op.f('ix_lem_rels_target_id'), 'lem_rels', ['target_id'], unique=False)
    op.create_table('lessons_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=48), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_lists_title'), 'lessons_lists', ['title'], unique=True)
    op.create_table('lookup_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('target_lem', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('rel_type', sa.Enum('ADJECTIVE_OF', 'ABSTRACT_NOUN_OF', 'ADVERB_OF', 'REL_ADJV_OF', 'NOUN_FROM_VERB_OF', 'PERFECTIVE_PAIR_OF', 'IMPERFECTIVE_PAIR_OF', 'SYNONYM_OF', 'ANTONYM_OF', name='enumrellemtype'), nullable=False),
    sa.Column('status', sa.Enum('UNLINKED', 'LINKED', 'FAILED', 'IGNORED', 'NOT_IN_DICT', name='enumlookupstatus'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['lemmas.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['lemmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lookup_queue_rel_type'), 'lookup_queue', ['rel_type'], unique=False)
    op.create_index(op.f('ix_lookup_queue_source_id'), 'lookup_queue', ['source_id'], unique=False)
    op.create_index(op.f('ix_lookup_queue_status'), 'lookup_queue', ['status'], unique=False)
    op.create_index(op.f('ix_lookup_queue_target_id'), 'lookup_queue', ['target_id'], unique=False)
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sent_idx', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sentences_doc_id'), 'sentences', ['doc_id'], unique=False)
    op.create_table('users_in_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['user_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('word_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lem_id', sa.Integer(), nullable=False),
    sa.Column('lex_id', sa.Integer(), nullable=False),
    sa.Column('gram_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gram_id'], ['gram_props.id'], ),
    sa.ForeignKeyConstraint(['lem_id'], ['lemmas.id'], ),
    sa.ForeignKeyConstraint(['lex_id'], ['lexicon.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_forms_gram_id'), 'word_forms', ['gram_id'], unique=False)
    op.create_index(op.f('ix_word_forms_lem_id'), 'word_forms', ['lem_id'], unique=False)
    op.create_index(op.f('ix_word_forms_lex_id'), 'word_forms', ['lex_id'], unique=False)
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ex_id', sa.Integer(), nullable=False),
    sa.Column('order_in_ex', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('LEM_TO_POS', 'POS_TO_LEM', 'LEM_TO_DEF', 'DEF_TO_LEM', 'LEM_TO_PRON', 'PRON_TO_LEM', 'LEM_LEM_TO_REL', 'REL_TO_LEM_LEM', 'ADJV_FORM_TO_TYPE', 'ADJV_TYPE_TO_LEM', 'ADJV_FORM_TO_GRAM', 'ADJV_GRAM_TO_FORM', 'NOUN_TO_GEND', 'GEND_TO_NOUN', 'NOUN_TO_ANIM', 'ANIM_TO_NOUN', 'NOUN_FORM_TO_GRAM', 'NOUN_GRAM_TO_FORM', 'NOUN_TO_DMIN_FORM', 'PART_TYPE_TO_FORM', 'PART_FORM_TO_TYPE', 'VERB_TO_ASPT', 'ASPT_TO_VERB', 'VERB_PAIR_TO_REL', 'VERB_TO_ASPT_PAIR', 'VERB_TO_TYPE', 'TYPE_TO_VERB', 'VERB_TO_CONJ_FORM', 'VERB_TO_TNRF', 'TNRF_TO_VERB', name='enumworditemtype'), nullable=False),
    sa.Column('item_format', sa.Enum('FITB', 'MCQ', 'FLASHCARD', name='enumitemformat'), nullable=False),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('finish_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ex_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_items_ex_id'), 'items', ['ex_id'], unique=False)
    op.create_index(op.f('ix_items_item_format'), 'items', ['item_format'], unique=False)
    op.create_index(op.f('ix_items_item_type'), 'items', ['item_type'], unique=False)
    op.create_index(op.f('ix_items_order_in_ex'), 'items', ['order_in_ex'], unique=False)
    op.create_table('lems_in_less_lists',
    sa.Column('lem_id', sa.Integer(), nullable=False),
    sa.Column('less_list_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lem_id'], ['lemmas.id'], ),
    sa.ForeignKeyConstraint(['less_list_id'], ['lessons_lists.id'], ),
    sa.PrimaryKeyConstraint('lem_id', 'less_list_id')
    )
    op.create_table('less_lists_in_mods',
    sa.Column('less_list_id', sa.Integer(), nullable=False),
    sa.Column('mod_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['less_list_id'], ['lessons_lists.id'], ),
    sa.ForeignKeyConstraint(['mod_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('less_list_id', 'mod_id')
    )
    op.create_table('sentence_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_id', sa.Integer(), nullable=False),
    sa.Column('token_idx', sa.Integer(), nullable=False),
    sa.Column('lex_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lem_raw', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('head_idx', sa.Integer(), nullable=True),
    sa.Column('dep_rel', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('semantic_tag', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_capitalized', sa.Boolean(), nullable=False),
    sa.Column('punctuation_before', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('punctuation_after', sqlmodel.sql.sqltypes.AutoString(length=8), nullable=True),
    sa.Column('status', sa.Enum('UNLINKED', 'LINKED', 'FAILED', 'IGNORED', 'NOT_IN_DICT', name='enumlookupstatus'), nullable=False),
    sa.Column('lem_id', sa.Integer(), nullable=True),
    sa.Column('lex_id', sa.Integer(), nullable=True),
    sa.Column('wf_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lem_id'], ['lemmas.id'], ),
    sa.ForeignKeyConstraint(['lex_id'], ['lexicon.id'], ),
    sa.ForeignKeyConstraint(['sent_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['wf_id'], ['word_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentence_token_features_gin', 'sentence_tokens', ['features'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_sentence_tokens_lem_id'), 'sentence_tokens', ['lem_id'], unique=False)
    op.create_index(op.f('ix_sentence_tokens_lex_id'), 'sentence_tokens', ['lex_id'], unique=False)
    op.create_index(op.f('ix_sentence_tokens_sent_id'), 'sentence_tokens', ['sent_id'], unique=False)
    op.create_index(op.f('ix_sentence_tokens_status'), 'sentence_tokens', ['status'], unique=False)
    op.create_index(op.f('ix_sentence_tokens_wf_id'), 'sentence_tokens', ['wf_id'], unique=False)
    op.create_table('item_options',
    sa.Column('option_uuid', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('explanation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('option_uuid')
    )
    op.create_index(op.f('ix_item_options_item_id'), 'item_options', ['item_id'], unique=False)
    op.create_table('lems_in_items',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('lem_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['lem_id'], ['lemmas.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'lem_id')
    )
    op.create_table('student_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('selection', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=False),
    sa.Column('attempt_num', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_responses_item_id'), 'student_responses', ['item_id'], unique=False)
    op.create_index(op.f('ix_student_responses_user_id'), 'student_responses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_responses_user_id'), table_name='student_responses')
    op.drop_index(op.f('ix_student_responses_item_id'), table_name='student_responses')
    op.drop_table('student_responses')
    op.drop_table('lems_in_items')
    op.drop_index(op.f('ix_item_options_item_id'), table_name='item_options')
    op.drop_table('item_options')
    op.drop_index(op.f('ix_sentence_tokens_wf_id'), table_name='sentence_tokens')
    op.drop_index(op.f('ix_sentence_tokens_status'), table_name='sentence_tokens')
    op.drop_index(op.f('ix_sentence_tokens_sent_id'), table_name='sentence_tokens')
    op.drop_index(op.f('ix_sentence_tokens_lex_id'), table_name='sentence_tokens')
    op.drop_index(op.f('ix_sentence_tokens_lem_id'), table_name='sentence_tokens')
    op.drop_index('ix_sentence_token_features_gin', table_name='sentence_tokens', postgresql_using='gin')
    op.drop_table('sentence_tokens')
    op.drop_table('less_lists_in_mods')
    op.drop_table('lems_in_less_lists')
    op.drop_index(op.f('ix_items_order_in_ex'), table_name='items')
    op.drop_index(op.f('ix_items_item_type'), table_name='items')
    op.drop_index(op.f('ix_items_item_format'), table_name='items')
    op.drop_index(op.f('ix_items_ex_id'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_word_forms_lex_id'), table_name='word_forms')
    op.drop_index(op.f('ix_word_forms_lem_id'), table_name='word_forms')
    op.drop_index(op.f('ix_word_forms_gram_id'), table_name='word_forms')
    op.drop_table('word_forms')
    op.drop_table('users_in_groups')
    op.drop_index(op.f('ix_sentences_doc_id'), table_name='sentences')
    op.drop_table('sentences')
    op.drop_index(op.f('ix_lookup_queue_target_id'), table_name='lookup_queue')
    op.drop_index(op.f('ix_lookup_queue_status'), table_name='lookup_queue')
    op.drop_index(op.f('ix_lookup_queue_source_id'), table_name='lookup_queue')
    op.drop_index(op.f('ix_lookup_queue_rel_type'), table_name='lookup_queue')
    op.drop_table('lookup_queue')
    op.drop_index(op.f('ix_lessons_lists_title'), table_name='lessons_lists')
    op.drop_table('lessons_lists')
    op.drop_index(op.f('ix_lem_rels_target_id'), table_name='lem_rels')
    op.drop_index(op.f('ix_lem_rels_source_id'), table_name='lem_rels')
    op.drop_table('lem_rels')
    op.drop_index(op.f('ix_lem_prons_pron_id'), table_name='lem_prons')
    op.drop_index(op.f('ix_lem_prons_lem_id'), table_name='lem_prons')
    op.drop_table('lem_prons')
    op.drop_index(op.f('ix_lem_defs_lem_id'), table_name='lem_defs')
    op.drop_index(op.f('ix_lem_defs_def_id'), table_name='lem_defs')
    op.drop_table('lem_defs')
    op.drop_index(op.f('ix_exercises_user_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_def_exs_ex_id'), table_name='def_exs')
    op.drop_index(op.f('ix_def_exs_def_id'), table_name='def_exs')
    op.drop_table('def_exs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_user_settings_gin', table_name='users', postgresql_using='gin')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_groups_group_name'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_table('pronunciations')
    op.drop_table('modules')
    op.drop_index(op.f('ix_lexicon_lex_text_clean'), table_name='lexicon')
    op.drop_index(op.f('ix_lexicon_lex_text'), table_name='lexicon')
    op.drop_table('lexicon')
    op.drop_index(op.f('ix_lemmas_lem_text'), table_name='lemmas')
    op.drop_index(op.f('ix_lemmas_lem_canon'), table_name='lemmas')
    op.drop_index(op.f('ix_lemmas_entry_key'), table_name='lemmas')
    op.drop_table('lemmas')
    op.drop_table('gram_props')
    op.drop_table('examples')
    op.drop_table('documents')
    op.drop_table('definitions')
    # ### end Alembic commands ###