"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints


# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = 'a09e7cfd6c7e'
down_revision: Union[str, None] = 'f52b256e23f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lookup_queue', sa.Column('requested_by', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_lookup_queue_requested_by'), 'lookup_queue', ['requested_by'], unique=False)
    op.create_foreign_key(None, 'lookup_queue', 'users', ['requested_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lookup_queue', type_='foreignkey')
    op.drop_index(op.f('ix_lookup_queue_requested_by'), table_name='lookup_queue')
    op.drop_column('lookup_queue', 'requested_by')
    # ### end Alembic commands ###