"""
ALITE Database Migration Revision
Template: alembic/script.py.mako

Engineering Justification:
- Injects standard typing and SQLModel dependencies automatically into every 
  generated migration script.
- Prevents runtime NameErrors during CI/CD pipeline deployments by ensuring 
  'sqlmodel' is always in the module namespace when applying schema changes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# ==============================================================================
# ALITE Custom Framework Imports
# ==============================================================================
import sqlmodel  # Required for SQLModel-specific column types and constraints


# ==============================================================================
# Alembic Revision Identifiers
# ==============================================================================
revision: str = 'abd901560985'
down_revision: Union[str, None] = '3a55bf200a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Apply schema changes to the PostgreSQL database.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_responses', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_responses_user_id'), 'student_responses', ['user_id'], unique=False)
    op.create_foreign_key(None, 'student_responses', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Revert schema changes, restoring the previous stable database state.
    Autogenerated operations are injected into this block by the Mako engine.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_responses', type_='foreignkey')
    op.drop_index(op.f('ix_student_responses_user_id'), table_name='student_responses')
    op.drop_column('student_responses', 'user_id')
    # ### end Alembic commands ###